name = "virtue-wear"
compatibility_date = "2024-09-14"

pages_build_output_dir = "dist"

# Custom domain configuration will be set up through Cloudflare dashboard
# Target domain: VirtueWear.pages.dev