name = "virtual-tryon-backend"
main = "src/index.js"
compatibility_date = "2024-09-15"

[[kv_namespaces]]
binding = "SESSIONS"
id = "3c8903f93f4247beb86ed3de9608dc1c"

[vars]
CORS_ORIGIN = "*"
SESSION_DURATION = "86400"